# Generated by Django 4.2.8 on 2023-12-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'verbose_name': 'Submenu'},
        ),
        migrations.AddField(
            model_name='submenu',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='menu.menu', verbose_name='Название меню'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название подменю'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.submenu', verbose_name='Родитель'),
        ),
    ]
